# Generated by Django 5.1.6 on 2025-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('matched_skills', models.TextField(blank=True, null=True)),
                ('match_percentage', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Shortlisted', 'Shortlisted'), ('Waiting List', 'Waiting List'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
