# Generated by Django 4.2 on 2025-04-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_jobapplication_job_alter_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.job')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.job')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.job')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobapplication')),
            ],
        ),
    ]
